services:
  postgres:
    container_name: lobi-postgres-staging
    volumes:
      - db_data_staging:/var/lib/postgresql/data

  backend:
    container_name: lobi-backend-staging

  nginx:
    container_name: lobi-nginx-staging
    ports:
      - "${STAGING_NGINX_PORT}:80"

volumes:
  db_data_staging:
