services:
  postgres:
    container_name: lobi-postgres-prod
    volumes:
      - db_data_prod:/var/lib/postgresql/data

  backend:
    container_name: lobi-backend-prod

  nginx:
    container_name: lobi-nginx-prod
    ports:
      - "${PROD_NGINX_PORT}:80"

volumes:
  db_data_prod:
